# Generated by Django 4.1.1 on 2022-10-11 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("machines", "0004_alter_machine_machine_group_and_more"),
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancereport",
            name="description",
            field=models.TextField(help_text="Description"),
        ),
        migrations.AlterField(
            model_name="maintenancereport",
            name="image",
            field=models.ImageField(
                help_text="Allowed formats (.jpg, .png)",
                upload_to="media/maintenance_reports",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancereport",
            name="schedule",
            field=models.ForeignKey(
                help_text="Corresponding maintenance schedule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="maintenance.maintenanceschedule",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancereport",
            name="user",
            field=models.ForeignKey(
                help_text="Serviceman",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceschedule",
            name="machine",
            field=models.ForeignKey(
                help_text="Machine",
                on_delete=django.db.models.deletion.CASCADE,
                to="machines.machine",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceschedule",
            name="maintenance_type",
            field=models.ForeignKey(
                help_text="Maintenance type",
                on_delete=django.db.models.deletion.CASCADE,
                to="maintenance.maintenancetype",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceschedule",
            name="planned_date",
            field=models.DateField(help_text="Maintenance planned date"),
        ),
        migrations.AlterField(
            model_name="maintenanceschedule",
            name="user",
            field=models.ForeignKey(
                help_text="Responsible",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetype",
            name="description",
            field=models.TextField(help_text="Description"),
        ),
        migrations.AlterField(
            model_name="maintenancetype",
            name="machine_group",
            field=models.ForeignKey(
                help_text="Machine group",
                on_delete=django.db.models.deletion.CASCADE,
                to="machines.machinegroup",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetype",
            name="type",
            field=models.CharField(
                choices=[
                    ("week", "weekly maintenance"),
                    ("month", "monthly maintenance"),
                    ("half year", "half year maintenance"),
                    ("year", "annual maintenance"),
                    ("two-years", "two years maintenacne"),
                    ("three-years", "three years maintenance"),
                    ("additional", "non-standard maintenacne"),
                ],
                default="week",
                help_text="Maintenance type",
                max_length=50,
            ),
        ),
    ]
