# Generated by Django 4.1.1 on 2022-10-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_alter_maintenancereport_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancetype",
            name="type",
            field=models.CharField(
                choices=[
                    ("week", "weekly maintenance"),
                    ("month", "monthly maintenance"),
                    ("half-year", "half year maintenance"),
                    ("year", "annual maintenance"),
                    ("two-years", "two years maintenacne"),
                    ("three-years", "three years maintenance"),
                    ("additional", "non-standard maintenacne"),
                ],
                default="week",
                help_text="Maintenance type",
                max_length=50,
            ),
        ),
    ]
