# Generated by Django 4.1.1 on 2022-10-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_alter_maintenancetype_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancereport",
            name="schedule",
            field=models.OneToOneField(
                help_text="Corresponding maintenance schedule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="maintenance.maintenanceschedule",
            ),
        ),
    ]
