# Generated by Django 4.1.1 on 2022-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0004_alter_maintenancereport_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceschedule",
            name="status",
            field=models.CharField(
                choices=[("pending", "pending"), ("done", "done")],
                default="pending",
                help_text="Schedule status (pending/available",
                max_length=7,
            ),
        ),
    ]
