# Generated by Django 4.1.1 on 2022-10-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0005_maintenanceschedule_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancereport",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Allowed formats (.jpg, .png)",
                upload_to="media/maintenance_reports",
            ),
        ),
    ]
