# Generated by Django 4.1.1 on 2022-11-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Machine group", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factory_number",
                    models.CharField(help_text="Factory number", max_length=100),
                ),
                (
                    "name",
                    models.CharField(help_text="Machine name(model)", max_length=100),
                ),
                (
                    "number",
                    models.CharField(help_text="Department number", max_length=100),
                ),
                ("producer", models.CharField(help_text="Producer", max_length=100)),
                (
                    "purchase_data",
                    models.DateField(blank=True, help_text="Purchase date", null=True),
                ),
                (
                    "machine_status",
                    models.CharField(
                        choices=[
                            ("available", "working fine"),
                            ("malfunction", "not working"),
                        ],
                        default="available",
                        help_text="Machine status (available/not working)",
                        max_length=32,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.department",
                    ),
                ),
                (
                    "machine_group",
                    models.ForeignKey(
                        help_text="Machine group",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="machines.machinegroup",
                    ),
                ),
            ],
        ),
    ]
