# Generated by Django 4.1.1 on 2022-09-26 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("malfunctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="media/malfunction_reports")),
                (
                    "machine",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="machines.machine",
                    ),
                ),
                (
                    "malfunction_report",
                    models.OneToOneField(
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="malfunctions.malfunctionreport",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MalfunctionPending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="machines.machine",
                    ),
                ),
                (
                    "malfunction_report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="malfunctions.malfunctionreport",
                    ),
                ),
            ],
        ),
    ]
