# Generated by Django 4.1.1 on 2022-10-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("malfunctions", "0002_malfunctionreport_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicereport",
            name="machine",
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="image",
            field=models.ImageField(blank=True, upload_to="media/malfunction_reports"),
        ),
    ]
