# Generated by Django 4.1.1 on 2022-10-08 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("malfunctions", "0003_remove_servicereport_machine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicereport",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
