# Generated by Django 4.1.1 on 2022-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("malfunctions", "0004_alter_servicereport_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicereport",
            name="service",
            field=models.CharField(
                choices=[("pending", "pending"), ("finished", "finished")],
                default="pending",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="image",
            field=models.ImageField(blank=True, upload_to="media/service_reports"),
        ),
    ]
