# Generated by Django 4.1.1 on 2022-10-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("malfunctions", "0005_servicereport_service_alter_servicereport_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicereport",
            name="malfunction_report",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="malfunctions.malfunctionreport",
            ),
        ),
    ]
