# Generated by Django 4.1.1 on 2022-10-11 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0003_alter_machine_purchase_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("malfunctions", "0006_alter_servicereport_malfunction_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="malfunctionreport",
            name="description",
            field=models.TextField(help_text="Description"),
        ),
        migrations.AlterField(
            model_name="malfunctionreport",
            name="image",
            field=models.ImageField(
                help_text="Allowed format (.jpg, .png)",
                upload_to="media/malfunction_issues",
            ),
        ),
        migrations.AlterField(
            model_name="malfunctionreport",
            name="machine",
            field=models.ForeignKey(
                help_text="Machine",
                on_delete=django.db.models.deletion.CASCADE,
                to="machines.machine",
            ),
        ),
        migrations.AlterField(
            model_name="malfunctionreport",
            name="status",
            field=models.CharField(
                choices=[("pending", "pending"), ("finished", "finished")],
                default="pending",
                help_text="Machine status",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="malfunctionreport",
            name="user",
            field=models.ForeignKey(
                default=0,
                help_text="Reporting user",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="description",
            field=models.TextField(help_text="Description"),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Allowed formats (.png, .jpg)",
                upload_to="media/service_reports",
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="malfunction_report",
            field=models.ForeignKey(
                default=0,
                help_text="Corresponding malfunction report",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="malfunctions.malfunctionreport",
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="service",
            field=models.CharField(
                choices=[("pending", "pending"), ("finished", "finished")],
                default="pending",
                help_text="Status after service",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="user",
            field=models.ForeignKey(
                default=0,
                help_text="Serviceman",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="MalfunctionPending",
        ),
    ]
