# Generated by Django 4.1.1 on 2022-10-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("malfunctions", "0007_alter_malfunctionreport_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="malfunctionreport",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Allowed format (.jpg, .png)",
                upload_to="media/malfunction_issues",
            ),
        ),
    ]
