# Generated by Django 4.1.1 on 2022-10-11 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_alter_department_name"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                default=1,
                help_text="Department",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="departments.department",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, help_text="Email", max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, help_text="First name", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("electrican", "electrican"),
                    ("mechanic", "mechanic"),
                    ("automation_serviceman", "automation serviceman"),
                    ("maintenance_supervisor", "maintenance supervisor"),
                    ("department_supervisor", "department supervisor"),
                    ("production_worker", "production worker"),
                ],
                help_text="Function",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manager", "manager"),
                    ("maintenance", "maintenance"),
                    ("production", "production"),
                ],
                help_text="Privileges group",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, help_text="Last name", max_length=70),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(blank=True, help_text="Mobile", max_length=12),
        ),
    ]
