# Generated by Django 4.1.1 on 2022-11-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("machines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(help_text="Description")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Allowed formats (.jpg, .png)",
                        upload_to="media/maintenance_reports",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("week", "weekly maintenance"),
                            ("month", "monthly maintenance"),
                            ("half-year", "half year maintenance"),
                            ("year", "annual maintenance"),
                            ("two-years", "two years maintenacne"),
                            ("three-years", "three years maintenance"),
                            ("additional", "non-standard maintenacne"),
                        ],
                        default="week",
                        help_text="Maintenance type",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(help_text="Description")),
                (
                    "machine_group",
                    models.ForeignKey(
                        help_text="Machine group",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="machines.machinegroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(help_text="Maintenance planned date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pending"), ("done", "done")],
                        default="pending",
                        help_text="Schedule status (pending/available",
                        max_length=7,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        help_text="Machine",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="machines.machine",
                    ),
                ),
                (
                    "maintenance_type",
                    models.ForeignKey(
                        help_text="Maintenance type",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.maintenancetype",
                    ),
                ),
            ],
        ),
    ]
