# Generated by Django 4.1.1 on 2022-09-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factory_number", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=100)),
                ("producer", models.CharField(max_length=100)),
                ("purchase_data", models.DateField()),
                (
                    "machine_status",
                    models.CharField(
                        choices=[
                            ("available", "working fine"),
                            ("nonwork", "not working"),
                            ("attention", "need some repairs but working"),
                        ],
                        default="available",
                        max_length=32,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.department",
                    ),
                ),
                (
                    "machine_group",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="machines.machinegroup",
                    ),
                ),
            ],
        ),
    ]
