# Generated by Django 4.1.1 on 2022-10-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0002_alter_machine_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="purchase_data",
            field=models.DateField(blank=True, help_text="Purchase date", null=True),
        ),
    ]
