# Generated by Django 4.1.1 on 2022-10-11 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0003_alter_machine_purchase_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="machine_group",
            field=models.ForeignKey(
                help_text="Machine group",
                on_delete=django.db.models.deletion.CASCADE,
                to="machines.machinegroup",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="machine_status",
            field=models.CharField(
                choices=[("available", "working fine"), ("malfunction", "not working")],
                default="available",
                help_text="Machine status (available/not working)",
                max_length=32,
            ),
        ),
    ]
